Contributing docs
neighbourhoodie/openpgpjs pull request #5
Opened 2023-11-22 15:06 UTC by AlbaHerrerias

What is missing:

- [ ]  Code of conduct (Alba on it)
- [ ]  BUG_REPORT template
- [ ]  PULL_REQUEST template
- [ ] Document release process

2023-11-22 15:46 UTC, espy requested changes
Only smol comments

2023-11-22 15:46 UTC, espy commented on CONTRIBUTING.md
> +**_NOTE:_**: You need to configure you env with `BROWSER_STACK_ACCESS_KEY` and `BROWSERSTACK_USERNAME` to be able to run the BrowserStack tests.
double `:`

2023-11-22 15:46 UTC, espy commented on CONTRIBUTING.md
> +(under `/benchmarks`) to avoid performance regressions, we measure time and memory usage with the following testing suites:
```suggestion
To avoid performance regressions, we measure time and memory usage with the following testing suites (in `/benchmarks`):
```

2023-11-22 15:46 UTC, espy commented on CONTRIBUTING.md
> +**Coverage**.
No periods at the end of headlines, I'd say

2023-11-22 15:46 UTC, espy commented on CONTRIBUTING.md
> +First of all, thank you for your contribution! Sit and relax. Someone from the team will review your PR and respond with comments as soon as possible (usually within a few weeks). Once you have addre
```suggestion
First of all, thank you for your contribution! Sit back and relax. Someone from the team will review your PR and respond with comments as soon as possible (usually within a few weeks). Once you have addressed all the comments, your PR will be approved and merged.
```

2023-11-22 15:46 UTC, espy commented on README.md
> +You want to help, great! We have two guides for you to read: [our new contributors](https://github.com/openpgpjs/openpgpjs/blob/main/NEW-CONTRIBUTORS.md) guide, and afterwards you can take a look at
Maybe omit `new`, this is probably going to stay this way for a long time

2023-11-22 15:46 UTC, espy commented on CONTRIBUTING.md
> +Please let us know you want to work on it so we can avoid multiple people working on the same issue. Ideally, notify us by our [Gitter](https://gitter.im/openpgpjs/openpgpjs), but expressing your int
```suggestion
Please let us know you want to work on it so we can avoid multiple people working on the same issue. Ideally, notify us by our [Gitter](https://gitter.im/openpgpjs/openpgpjs), but expressing your interest in the issue itself is also ok.
```

2023-11-23 10:04 UTC, AlbaHerrerias commented on README.md
> +You want to help, great! We have two guides for you to read: [our new contributors](https://github.com/openpgpjs/openpgpjs/blob/main/NEW-CONTRIBUTORS.md) guide, and afterwards you can take a look at
This `new` is from the `NEW-CONTRIBUTORS.md` guide, should I refrase it to make it more clear?

2023-11-23 10:45 UTC, AlbaHerrerias commented on README.md
> +You want to help, great! We have two guides for you to read: [our new contributors](https://github.com/openpgpjs/openpgpjs/blob/main/NEW-CONTRIBUTORS.md) guide, and afterwards you can take a look at
How about `our guide for new contributors`?

2023-11-23 10:58 UTC, espy commented on README.md
> +You want to help, great! We have two guides for you to read: [our new contributors](https://github.com/openpgpjs/openpgpjs/blob/main/NEW-CONTRIBUTORS.md) guide, and afterwards you can take a look at
🤦‍♂️i can’t read. Yeah, that’s a good solution!

2023-11-29 15:35 UTC, espy requested changes

2023-11-29 15:35 UTC, espy commented on .github/ISSUE_TEMPLATE/BUG_REPORT.md
> +- Have you search existing issues and discussions about your problem? Your problem might be already solved, and this could avoid creating duplicates
```suggestion
- Have you searched existing issues and discussions about your problem? Your problem might be already solved, and this could avoid creating duplicates
```

2023-11-29 15:35 UTC, espy commented on .github/ISSUE_TEMPLATE/BUG_REPORT.md
> +- Is this a implementation or support question? If so, open a discussion here https://github.com/openpgpjs/openpgpjs/discussions/categories/q-a
```suggestion
- Is this an implementation or support question? If so, open a discussion here https://github.com/openpgpjs/openpgpjs/discussions/categories/q-a 
```

2023-11-29 15:35 UTC, espy commented on .github/ISSUE_TEMPLATE/BUG_REPORT.md
> +- Code snippets (so we can reproduce it). As minimal and precisely as possible
```suggestion
- Code snippets (so we can reproduce it). As minimal and precisely as possible. Please put these in appropriate code fences for better readabilty.
```

2023-11-29 15:35 UTC, espy commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--  Thank you for sending a pull request! Please take a moment to review:
```suggestion
<!--  Thank you for sending a pull request! Please take a moment to review the following:
```

2023-11-29 15:35 UTC, espy commented on .github/PULL_REQUEST_TEMPLATE.md
> +- If this is your first time, please read our guide for new contributors https://github.com/openpgpjs/openpgpjs/blob/main/NEW-CONTRIBUTORS.md and our general contributing guide https://github.com/ope
```suggestion
- If this is your first contribution, please read our guide for new contributors https://github.com/openpgpjs/openpgpjs/blob/main/NEW-CONTRIBUTORS.md and our general contributing guide https://github.com/openpgpjs/openpgpjs/blob/main/CONTRIBUTING.md
```

2023-11-29 15:35 UTC, espy commented on .github/PULL_REQUEST_TEMPLATE.md
> +- Make sure that you have added or ran the appropriate tests https://github.com/openpgpjs/openpgpjs/blob/main/CONTRIBUTING.md#testing
```suggestion
- Make sure that you have added or run the appropriate tests https://github.com/openpgpjs/openpgpjs/blob/main/CONTRIBUTING.md#testing
```

2023-11-29 15:35 UTC, espy commented on .github/PULL_REQUEST_TEMPLATE.md
> +- If your PR is not finished, mark it as draft
```suggestion
- If your PR is not finished, please mark it as a draft
```

2023-11-29 15:35 UTC, espy commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Explain what this PR does and why do we need it  -->
```suggestion
<!-- Explain what this PR does and why we need it  -->
```

2023-11-29 15:35 UTC, espy commented on CONTRIBUTING.md
> +If you are looking for something to work on, we try to maintain a list of issues that should be suitable for first time contributions, they can be found tagged [`good-first-issue`](https://github.com
```suggestion
If you are looking for something to work on, we try to maintain a list of issues that should be suitable for first time contributions, they can be found tagged [`good-first-issue`](https://github.com/openpgpjs/openpgpjs/labels/good-first-issue). You can also look through our issues and pick some you like. If you're still unsure, please [reach out](#communication) and we would help you to the best of our abilities.
```

2023-11-29 15:35 UTC, espy commented on CONTRIBUTING.md
> +Please let us know you want to work on it so we can avoid multiple people working on the same issue. Ideally, notify us by our [Gitter](https://gitter.im/openpgpjs/openpgpjs), but expressing your int
```suggestion
Please let us know you want to work on it so we can avoid multiple people working on the same issue. Ideally, notify us via our [Gitter](https://gitter.im/openpgpjs/openpgpjs), but expressing your interest in the issue itself is also ok.
```

2023-11-29 15:35 UTC, espy commented on MAINTAINERS.md
> +We keep it simple. We use npm's `version` command as following:
```suggestion
We keep it simple. We use npm’s `version` command as following:
```
Extreme typography nitpick, sorry 🙈

2023-11-29 15:51 UTC, espy approved these changes

2023-12-13 10:54 UTC, merged